import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { getSessionUserId } from "@/lib/session";
import { decryptJson } from "@/lib/crypto";
import { getDb } from "@/lib/db";
import {
  SpotifyApiError,
  addItemsToPlaylist,
  createPlaylist,
  refreshAccessToken,
  spotifySearchTracks
} from "@/lib/spotify";
import { createRequestId } from "@/lib/request-id";
import { checkRateLimit } from "@/lib/rate-limit";
import type { TrackCandidate } from "@/lib/types";

export const runtime = "nodejs";

const schema = z.object({
  requestId: z.string().uuid(),
  name: z.string().min(3).max(80).optional(),
  length: z.number().int().min(25).max(100).optional().default(40),
  previewUris: z.array(z.string().min(8).max(256)).max(100).optional()
});

type TokenBundle = {
  refreshToken: string;
};

function buildTrackPreview(prompt: string, length: number, trackResults: TrackCandidate[]): TrackCandidate[] {
  const picked: TrackCandidate[] = [];
  const seenUris = new Set<string>();
  const seenArtists = new Set<string>();

  for (const track of trackResults) {
    if (seenUris.has(track.uri)) {
      continue;
    }

    const primaryArtist = track.artistNames[0]?.toLowerCase();
    const isDuplicateArtist = primaryArtist ? seenArtists.has(primaryArtist) : false;
    if (isDuplicateArtist && picked.length < Math.max(10, Math.floor(length * 0.6))) {
      continue;
    }

    picked.push(track);
    seenUris.add(track.uri);
    if (primaryArtist) {
      seenArtists.add(primaryArtist);
    }

    if (picked.length >= length) {
      break;
    }
  }

  if (picked.length === 0) {
    throw new Error(`No matching tracks found for prompt: ${prompt.slice(0, 80)}`);
  }

  return picked;
}

export async function POST(request: NextRequest): Promise<NextResponse> {
  try {
    const ip = request.headers.get("x-forwarded-for") ?? "local";
    const rate = checkRateLimit(`generate:${ip}`);

    if (!rate.allowed) {
      return NextResponse.json(
        {
          error: {
            code: "rate_limited",
            message: "Too many generate attempts. Retry shortly.",
            retryAfterSec: rate.retryAfterSec
          }
        },
        { status: 429 }
      );
    }

    const userId = await getSessionUserId();

    const body = await request.json().catch(() => null);
    const parsed = schema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json(
        { error: { code: "bad_request", message: "Invalid generate payload." } },
        { status: 400 }
      );
    }

    const db = getDb();

    const vibeReq = db
      .prepare(`SELECT prompt FROM vibe_requests WHERE id = ?`)
      .get(parsed.data.requestId) as { prompt: string } | undefined;

    if (!vibeReq) {
      return NextResponse.json(
        { error: { code: "not_found", message: "Original recommendation request not found." } },
        { status: 404 }
      );
    }

    let accessToken: string | undefined;
    let previewTracks: TrackCandidate[] = [];

    if (!parsed.data.previewUris || parsed.data.previewUris.length === 0) {
      const queries = [vibeReq.prompt, `${vibeReq.prompt} playlist`, `${vibeReq.prompt} mix`];
      const foundTracks: TrackCandidate[] = [];

      for (const query of queries) {
        const found = await spotifySearchTracks(query, 10, accessToken);
        foundTracks.push(...found);
        if (foundTracks.length >= parsed.data.length * 3) {
          break;
        }
      }

      previewTracks = buildTrackPreview(vibeReq.prompt, parsed.data.length, foundTracks);
    }

    if (!userId) {
      return NextResponse.json({
        generationMode: "preview-only",
        note: "Preview generated from search-based track sampling. Log in to save it to Spotify.",
        tracks: previewTracks
      });
    }

    const user = db
      .prepare(`SELECT token_enc_blob FROM users WHERE id = ?`)
      .get(userId) as { token_enc_blob: string } | undefined;

    if (!user) {
      return NextResponse.json(
        { error: { code: "unauthorized", message: "Session user not found." } },
        { status: 401 }
      );
    }

    const bundle = decryptJson<TokenBundle>(user.token_enc_blob);
    const refreshed = await refreshAccessToken(bundle.refreshToken);
    accessToken = refreshed.access_token;

    const playlistName = parsed.data.name ?? `Vibeforge: ${vibeReq.prompt.slice(0, 40)}`;
    let created;
    try {
      created = await createPlaylist(
        accessToken,
        playlistName,
        `Generated by Vibeforge from vibe: ${vibeReq.prompt.slice(0, 120)}`
      );
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      return NextResponse.json(
        {
          error: {
            code: "spotify_error",
            message: `Playlist creation failed. ${message}. Verify Spotify app scope includes playlist-modify-private and re-login.`
          }
        },
        { status: 502 }
      );
    }

    try {
      await addItemsToPlaylist(
        accessToken,
        created.id,
        (parsed.data.previewUris && parsed.data.previewUris.length > 0
          ? parsed.data.previewUris
          : previewTracks.map((track) => track.uri))
      );
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      return NextResponse.json(
        {
          error: {
            code: "spotify_error",
            message: `Adding tracks failed. ${message}`
          }
        },
        { status: 502 }
      );
    }

    db.prepare(
      `INSERT INTO feedback (id, user_id, vibe_request_id, generated_playlist_id, rating, notes, created_at)
       VALUES (?, ?, ?, ?, ?, ?, ?)`
    ).run(
      createRequestId(),
      userId,
      parsed.data.requestId,
      created.id,
      1,
      "generated",
      new Date().toISOString()
    );

    return NextResponse.json({
      playlistId: created.id,
      playlistUrl: created.external_urls.spotify,
      generationMode: "search-fallback",
      note: "Created from search-based track sampling.",
      tracks: previewTracks
    });
  } catch (error) {
    if (error instanceof SpotifyApiError && error.status === 429) {
      return NextResponse.json(
        {
          error: {
            code: "rate_limited",
            message: "Spotify rate limit reached while building the playlist. Please retry shortly.",
            retryAfterSec: error.retryAfterSec ?? 10
          }
        },
        { status: 429 }
      );
    }
    const message = error instanceof Error ? error.message : String(error);
    return NextResponse.json(
      {
        error: {
          code: "spotify_error",
          message: `Playlist generation failed. ${message}`
        }
      },
      { status: 502 }
    );
  }
}
